### ISSUE TITLE
Start date documentation

### ISSUE THREAD

**Issue by TomSmithCGAT** [GreenAlgorithms/GreenAlgorithms4HPC#7]
https://github.com/GreenAlgorithms/GreenAlgorithms4HPC/blob/6d33be2722ee9b2075738f4d2f83e5dc24664a4f/README.md?plain=1#L26-L27

Is wrong. It should say 1st January for this year:

https://github.com/GreenAlgorithms/GreenAlgorithms4HPC/blob/6d33be2722ee9b2075738f4d2f83e5dc24664a4f/GreenAlgorithms_global.py#L384

**Comment by Llannelongue** [comment]
Thank you for spotting (and sorry it took me so long to get to it!). It's now fixed.
