### ISSUE TITLE
mem_raw in calc_reqMem throws "ValueError: could not convert string to float: ''"

### ISSUE THREAD

**Issue by FriederikeHanssen** [GreenAlgorithms/GreenAlgorithms4HPC#8]
Hi!

thanks for the awesome tool. I cloned it yesterday and I have tried it out on our SLURM cluster. I have run it using several of my job ids, but also with `--runTests coreHoursPerMonth`.

I constantly run into the following issue:

```
sh myCarbonFootprint.sh --runTests coreHoursPerMonth
Python versions: OK
Virtualenv: OK
Traceback (most recent call last):
  File "./GreenAlgorithms4HPC/GreenAlgorithms_global.py", line 437, in <module>
    main(args, cluster_info, fParams)
  File "./GreenAlgorithms4HPC/GreenAlgorithms_global.py", line 344, in main
    WM.clean_logs_df()
  File "./GreenAlgorithms4HPC/GreenAlgorithms_workloadManager.py", line 290, in clean_logs_df
    self.logs_df['ReqMemX'] = self.logs_df.apply(self.calc_ReqMem, axis=1)
  File "./GreenAlgorithms4HPC/GA_env/lib/python3.9/site-packages/pandas/core/frame.py", line 7768, in apply
    return op.get_result()
  File "./GreenAlgorithms4HPC/GA_env/lib/python3.9/site-packages/pandas/core/apply.py", line 185, in get_result
    return self.apply_standard()
  File "./GreenAlgorithms4HPC/GA_env/lib/python3.9/site-packages/pandas/core/apply.py", line 276, in apply_standard
    results, res_index = self.apply_series_generator()
  File "./GreenAlgorithms4HPC/GA_env/lib/python3.9/site-packages/pandas/core/apply.py", line 290, in apply_series_generator
    results[i] = self.f(v)
  File "./GreenAlgorithms4HPC/GreenAlgorithms_workloadManager.py", line 40, in calc_ReqMem
    memory = float(mem_raw[:-2])
ValueError: could not convert string to float: ''
```
I did some digging and printed out the `mem_raw` value that is retrieved for the failing job: `1G` as well as the 

```
unit: 1
per_coreOrNode: G
```

I guess `memory = float(mem_raw[:-2])` then fails, because there are only two positions in the string. however, I was also wondering if the retrieved values above are actually expected?

Let me know if any other of my configuration files would be of help :)

**Comment by FriederikeHanssen** [comment]
Did some more digging and noticed that my file looks very different to the example files, maybe because I submitted the jobs with nextflow? Do you have any idea how to get the desired values? I also have the `jobID.batch`, `jobID.extern`and just `jobID` columns, but for neither I get the desired format for `ReqMem`

[sacctOutput_test.csv](https://github.com/GreenAlgorithms/GreenAlgorithms4HPC/files/11412390/sacctOutput_test.csv)

**Comment by ADemortier** [comment]
Hi Friederike,
I had the same problem. I guess it was due to an update of Slurm.

An example from this command : mem_raw, n_nodes, n_cores = x['ReqMem'], x['NNodes'], x['NCPUS'], 
give me : 
mem_raw = 3211000M
n_nodes = 13
n_cores = 1664
There is no "n" or "c" at the end of mem_raw...
Moreover, it would be unnecessary to multiply the memory by the number of nodes, because it is already done (3211000/13 = 247000M, which should be the storage of a node).

Then I replaced the function "calc_ReqMem" by this corrected one : 
def calc_ReqMem(self, x):
        '''
        Calculate the total memory required when submitting the job.
        :param x: [pd.Series] one row of sacct output.
        :return: [float] total required memory, in GB.
        '''
        mem_raw, n_nodes, n_cores = x['ReqMem'], x['NNodes'], x['NCPUS']

        if not pd.isnull(mem_raw):
            unit = mem_raw[-1]
            per_coreOrNode = 'n' #mem_raw[-1]
            memory = float(mem_raw[:-1]) # Old : -2
        else : 
            unit = 'G'
            per_coreOrNode = 'n' 
            memory = 0 # No storage for unknown mem_raw
        
        # Convert memory to GB
        memory = self.convert_to_GB(memory,unit)
        return memory
        
I would be glad to know if the owner of the code agrees with this correction.

Thanks!
Alan

**Comment by Llannelongue** [comment]
Hi, thanks for flagging this and sorry for the delay! I'll try to sort this this week :)

**Comment by Llannelongue** [comment]
Sorry it took me so long to get to it! It's now fixed along the lines suggested (just added some code for back compatibility). It was indeed due to a SLURM update where the memory is not given by node or core anymore. Let me know if you spot any more issues!
